### ISSUE TITLE
[QUESTION] Why consumer in my case can't consume at least something?

### ISSUE THREAD

**Issue by UserBohdan123** [mateusjunges/laravel-kafka#206]
Hello. Let me ask a question. I can't find out what I am doing wrong.

I can produce topics with this component:
```
# php artisan demo:produce-demo-topic

Kafka::publishOn('demo_topic')
            ->withMessage(
                new Message(
                    body: [
                        'this' => 'is',
                        'demo' => 'topic',
                    ],
                )
            )
            ->send();
```
I can consume it with kafkacat
```
# kcat -C -b kafka-instance:19092 -t demo_topic

% Reached end of topic demo_topic [0] at offset 13
{"this":"is","demo":"topic"}
% Reached end of topic demo_topic [0] at offset 14
```
---
 
But I can't consume it with this component. 
```
# php artisan app:consume-demo-topic

 Kafka::createConsumer()
            ->subscribe('demo_topic')
            ->withHandler(
                function (KafkaConsumerMessage $message) {
                    logger('Consumed');
                }
            )
            ->build()
            ->consume();
```
I do produce some new topics, but the laravel log is empty and the process keeps running like everything is fine. 

What am I doing wrong?

Few things about my docker env

1. Laravel 10 app runs with PHP 8.2 and has installed kafkacat.
(kafkacat can consume and produce topics within this container)

2. Kafka app `docker-compose.yml`
```
zookeeper-server:
    image: confluentinc/cp-zookeeper:5.0.0
#...
 kafka-instance:
    image: confluentinc/cp-enterprise-kafka:5.0.0
    # ... 
    environment:
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-instance:19092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
```

Thanks in advance!
