### ISSUE TITLE
Failed to resolve `broker:9092`

### ISSUE THREAD

**Issue by akbarali1** [mateusjunges/laravel-kafka#271]
I have installed kafka on docker. The docker-compose.yml file is as follows.
```yml
version: "3.7"

services:
 zookeeper:
   image: zookeeper:3.7
   container_name: zookeeper
   ports:
     - "2181:2181"
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_SERVERS: zookeeper:2888:3888

 kafka1:
   image: wurstmeister/kafka
   container_name: kafka1
   ports:
     - "9092:9092"
   environment:
     KAFKA_ADVERTISED_HOST_NAME: kafka1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_BROKER_ID: 1
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   depends_on:
     - zookeeper

 kafka-ui:
   image: provectuslabs/kafka-ui:latest
   container_name: kafka-ui
   ports:
     - "8080:8080"
   environment:
     KAFKA_CLUSTERS_0_NAME: "kafka-local"
     KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"

```

My code 
![Screenshot 2024-03-19 at 14 20 59](https://github.com/mateusjunges/laravel-kafka/assets/39323182/d001ca4a-e2f4-4b9a-8686-c22402e7bf6a)

But I get the following error.

![Screenshot 2024-03-19 at 14 21 45](https://github.com/mateusjunges/laravel-kafka/assets/39323182/a2ff0f3a-9aad-4457-8cb9-640e55ef09dc)

How can I fix it? Where am I going wrong?
