### ISSUE TITLE
Message consuming is still an issue in v2.1

### ISSUE THREAD

**Issue by aungmyatmoethegreat** [mateusjunges/laravel-kafka#284]
# Producer
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Junges\Kafka\Facades\Kafka;
use Junges\Kafka\Message\Message;

class KafkaProduceMessageCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'saga:test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';


    /**
     * @throws \Exception
     */
    public function handle(): void
    {
        Kafka::publish()
            ->onTopic('saga')
            ->withMessage(new Message(body: 'Hello world!'))
            ->send();
    }
}

```

# Consumer
```php
<?php

namespace App\Console\Commands;

use Enqueue\RdKafka\RdKafkaConnectionFactory;
use Illuminate\Console\Command;
use Interop\Queue\Exception;
use Interop\Queue\Exception\InvalidDestinationException;
use Interop\Queue\Exception\InvalidMessageException;
use Junges\Kafka\Contracts\KafkaMessage;
use Junges\Kafka\Exceptions\ConsumerException;
use Junges\Kafka\Facades\Kafka;


class KafkaConsumerCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'saga:listen';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Saga';


    public function handle(): void
    {
        try {
            $consumer = Kafka::consumer(['saga'])
                ->withHandler(function (KafkaMessage $message) {
                    dump($message->getBody());
                })
                ->build();

            $consumer->consume();
        } catch (Exception $e) {
            dump($e->getMessage());
        } catch (\Carbon\Exceptions\Exception $e) {
            dump($e->getMessage());
        } catch (ConsumerException $e) {
            dump($e->getMessage());
        }

    }
}

```

I tried to change the Docker images, but the issue persists.

I am currently using Bitnami and CP-Kafka to test. Both of them are working well with the consuming process when I use them with Conduktor Console.

# Docker compose
```yml
  #  kafka:
  #    image: confluentinc/cp-kafka:7.4.0
  #    hostname: kafka
  #    container_name: kafka
  #    depends_on:
  #      - zookeeper
  #    ports:
  #      - "9092:9092"
  #      - "29092:29092"
  #    environment:
  #      KAFKA_BROKER_ID: 1
  #      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092


  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - development
    ports:
      - '9092:9092'
      - '9094:9094'
    #    volumes:
    #      - ./kafka:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      #  Listener settings
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://host.docker.internal:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
```

# Version

```json
        "mateusjunges/laravel-kafka": "^2.1",

```
