### ISSUE TITLE
I want to connect kafka cluster in laravel in this library is it possible(config multiple brokers)? and i have some problems with configuration error in laravel. can you help me?

### ISSUE THREAD

**Issue by Edision1** [mateusjunges/laravel-kafka#333]
Step 1: Install the Kafka Library for Laravel
      ` composer require junges/laravel-kafka`
Step 2: Create a Configuration File config/kafka.php
In this file, configure your Kafka brokers as follows:

```
php
return [
    'brokers' => env('KAFKA_BROKERS', 'localhost:9092'),
];
```
In .env file, I add the three broker addresses:
   ` KAFKA_BROKERS="192.168.1.100:9092,192.168.1.100:9093,192.168.1.100:9094"`
Step 3: Create a Command to Send a Kafka Message
Create the command SendKafkaMessage.php in the app/Console/Commands directory.

```
php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Junges\Kafka\Facades\Kafka;

class SendKafkaMessage extends Command
{
    protected $signature = 'kafka:send';
    protected $description = 'Send a message to Kafka';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        // Get brokers from the configuration
        $brokers = config('kafka.brokers');

        Kafka::publish($brokers)
            ->onTopic('my-topic')
            ->withBody('Test message from Laravel Kafka!')
            ->send();
    }
}
```
then i run command `php artisan kafka:send` but it message error: Your message could not be published. Flush returned with error code -185: 'Local: Timed out'. what is the rootcause ? I tried pushing it in terminal and it still works ? In which can I ping these IP addresses to terminal.

**Comment by Edision1** [comment]
Hi @mateusjunges, Can you help me answer the questions above?

**Comment by mateusjunges** [comment]
are you running kafka on docker? Also, what's your laravel version and what version of this package are you using?

**Comment by Edision1** [comment]
I not running kafka on docker and I use package kafka-laravel 1.8.

**Comment by Edision1** [comment]
```
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2181

  kafka-broker-1:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-1
    ports:
      - "9092:9093"
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://192.168.1.100:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENERS_OUTSIDE: OUTSIDE://192.168.1.100:9092
      KAFKA_LISTENER_PORT_OUTSIDE: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_OUTSIDE: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENER_OUTSIDE: 192.168.1.100:9092
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka-broker-2:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://192.168.1.100:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENERS_OUTSIDE: OUTSIDE://192.168.1.100:9093
      KAFKA_LISTENER_PORT_OUTSIDE: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_OUTSIDE: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENER_OUTSIDE: 192.168.1.100:9093
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka-broker-3:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker-3
    ports:
      - "9094:9093" 
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://192.168.1.100:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENERS_OUTSIDE: OUTSIDE://192.168.1.100:9094
      KAFKA_LISTENER_PORT_OUTSIDE: 9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_OUTSIDE: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENER_OUTSIDE: 192.168.1.100:9094
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
```
Can you help me see if the above configuration is correct? Do I need to configure anything else?
