### ISSUE TITLE
[QUESTION] Messages are not been sent

### ISSUE THREAD

**Issue by K2ouMais** [mateusjunges/laravel-kafka#98]
Hello there,

I am using a docker-compose file to have a local Kafka container.

docker-compose:
```
version: "2"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

On my Laravel project I set in the .env the KAFKA_BROKERS as following:
```
KAFKA_BROKERS="localhost:9092"
```

I did go to Kafdrop and opened a new topic:
http://localhost:9000
topic = test

This is the code in my controller to do some tests:
```
 $message = new Message(
            body: 'This is a new message'
        );

        Kafka::publishOn('test', 'localhost:9092')
            ->withMessage($message)
            ->withDebugEnabled()
            ->send();
```

It seems that I always get an Exception with the following error:
```
Sent messages may not be completed yet.
```

There arent any messages on the topic.

Am I doing anything wrong?

Thank you in advance
